### ISSUE TITLE
Duplicates on HNQIS 1.2.4

### ISSUE THREAD

**Issue by ifoche** [ifoche/malariapp#1503]

**Comment by ifoche** [comment]
DB of the user that's generating the duplicates here:
https://drive.google.com/open?id=0B3FU6Lx45t71UWxRRGxFRG1QT00

**Comment by ifoche** [comment]
The HNQIS app sends many duplicate events within seconds to the singapore-dev server - see this Event Report:
https://singapore-dev.psi-mis.org/dhis-web-event-reports/index.html?id=FHSvmwhUlA3

Also, here is the database of a country user:
https://drive.google.com/a/baosystems.com/file/d/0B3FU6Lx45t71b3hvWDZhWXN1MVU/view?usp=sharing

Name: Lal Khan Lam
Android version - 5.0.2
Model no: - SM-P555

original request:
The same score for 4 providers and a lot of assessments for these 4 with a difference in the push date of a handful of seconds (Dim Mawi (AMTR175666-01): 25 assessments, Nguint Mg (AMTR175581-03): 51 assessments, Shine Aung (AMTR175581-02): 51 assessments, U Davit (AMTR175666-04): 38 assessments).

**Comment by idelcano** [comment]
@ifoche This user doesn't pull the required controldataelement to control the quarantine surveys (_CreatedOn), without this controldataelement the quarantine system doesn't work, and will be sent.

I found other strange thing.. the User table has 15 pulled users... ( this happen in a new clean login with the provided user). But i think this is irrelevant for this problem.

Actually, when this user was disconnected before send a survey, this survey will be set as quarantine.
In the next attempts the app will be send the survey because the quarantine system doesn't work,  this causes the first duplicated. If the user has a bad network connection.. i think the response of the server can be time outed a lot of times, but the survey saved on the server, and the survey set as quarantine every push... and send again.
