### ISSUE TITLE
Refine all app design following mockup

### ISSUE THREAD

**Issue by ifoche** [ifoche/malariapp#1519]
As a guide, [this mockup](http://web2.beckolsystem.com/hnqis/#/screens/d9978ee8-0c5a-4d1e-9629-9d294141c92c) aims to provide an idea of the intention in terms of desired design changes

Another alternative design is [this one](http://web2.beckolsystem.com/hnqis-2/#/screens/d12245cc-1680-458d-89dd-4f0d7fb22724)

**Comment by idelcano** [comment]
@ifoche i created this guide to simplified the task, maybe you can delete some points if you think is not important at this moment

General:
- [x] filters style 
- [x] Remove action bar back button

Fragment Planning:
- [x] remove header
- [x] plan fragment colours and fonts and listview row
- [x] plan per orgunit colours and fonts and listview row
- [x] Change button

Fragment assess:
- [x] general cosmetic changes
- [x] listview row
- [x] Create pie instead of survey % complete
- [x] Change button
- [x] Add filters

Fragment improve:
- [x] general colours and fonts
- [x] listview row

- [x] Reschedule dialog
