### ISSUE TITLE
Review #1370 & #1371 to split it into multiple issue

### ISSUE THREAD

**Issue by ifoche** [ifoche/malariapp#1530]

**Comment by idelcano** [comment]
From issue # 1371:
# 1532 - Save response in dB
# 1533 - Change model by Survey throughout the application, this implies: add program domain entity, orgunit entity,  productivity entity and move productivity from survey model to survey domain. 
This allow use a score register with id instead of models
# 1532 - This will be removed..(create program and orgunit is necessary in #1533)
From issue #1370:
#1536 refactor getSurveyAnsweredRatioUseCase responsabilities
