### ISSUE TITLE
Share HTML feedback

### ISSUE THREAD

**Issue by ifoche** [ifoche/malariapp#1568]
This task involves:
- [ ] Creating the format to match as much as possible the design
- [ ] Share paying special attention to gmail sharing

**Comment by idelcano** [comment]
Working in: https://github.com/EyeSeeTea/malariapp/tree/feature-share_html_feedback

I tried it with Gmail, Inbox, the default mail client and Outlook. But it only works in Outlook.
I did not find so much information, only people commenting that feature is probably obsolete in gmail.
This example code should work, but never works, the text is converted to plain text:
```
        Intent emailIntent     = new Intent(android.content.Intent.ACTION_SEND);
        emailIntent.setType("text/html");
        emailIntent.putExtra(Intent.EXTRA_EMAIL,
                new String[]{"human@gmail.com"});
emailIntent.putExtra(android.content.Intent.EXTRA_SUBJECT, title);
        emailIntent.putExtra(Intent.EXTRA_TEXT, Html.fromHtml("<html><body><h1>Hello World</h1>Hello, here is some <b>bold text</b> some <u>underline text</u> and <a href=\"http://www.google.com\">a link</a>.</body><html>") );
        activity.startActivity(Intent.createChooser(emailIntent, "Share"));
```

And this example code is working only for the outlook app:

```
Intent emailIntent = new Intent();
        emailIntent.putExtra(Intent.EXTRA_EMAIL,
                new String[]{"human@gmail.com"});
        emailIntent.setType("text/html");
        emailIntent.putExtra(android.content.Intent.EXTRA_SUBJECT, title);
        emailIntent.putExtra(Intent.EXTRA_HTML_TEXT, "<html><body><h1>Hello World</h1>Hello, here is some <b>bold text</b> some <u>underline text</u> and <a href=\"http://www.google.com\">a link</a>.</body><html>" );
        activity.startActivity(emailIntent);
```
but using  Intent.EXTRA_HTML_TEXT gmail or Inbox the message is empty...

The newest versions of android gmail app include a text rich editor, and i didn't find a way to write html code in gmail android app, or web without extensions.
finally, i tried to find a way to send a text rich instead of html into the android intents. I don't found nothing.

**Comment by ifoche** [comment]
@manuelplazaspalacio assigning this issue to you, just in case you are able to do it. Please spend some time trying and if you don't get it done in some time, please contact me and we will try to find a solution

**Comment by idelcano** [comment]
http://web2.beckolsystem.com/hnqis/#/screens/6dc87837-756f-4d8a-a188-c06f9345e4be
