### ISSUE TITLE
Investigate why events arrive without _ProviderName

### ISSUE THREAD

**Issue by ifoche** [ifoche/malariapp#2031]
Alpha testers are complaining about events that are sent without _ProviderName DE attached. They're looking at the events using the Events Report app, whose starting point is aggregate data, but you can also check the events that are generating those aggregate (concretely, please [look at this screenshot](https://user-images.githubusercontent.com/12784825/41651831-301b5c06-748a-11e8-95a7-d91bce0be498.png)). So firstly, please check that events are not really being sent without that DE and it's not a bug in Events Report App or something like that.

**Comment by idelcano** [comment]
I uploaded a survey in data server with provider name, and i see it with the provider name, after the reports update.

![testprovider.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56153dcd2d55821100fa1eb5/125516c66e82c728ace21e0d46fc9189379291a699e0bb46b61fbcd6395428792c07b7692ac7b67cb91a7a02575b46a8130e5a41fdfe892ba7b36925dc5419f1c32f0e2a92624cf5f2d75dad0ba8218c4584b3bf8a4ac5ec3f24ee8e8d492c53.png)

When the UID of the control dataelement "provider name" is not downloaded, the app push the action plan ignoring that control dataelement.
I think the alpha tester pulled against data server when the provider name was not assigned to the KEdemo programs.

I think that problem was resolved the last week. ( i don't know who fix it. but i close t#1995 because the problem was solved)


The solution is make a new pull.

**Comment by ifoche** [comment]
[compressedData (33).zip](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/54e12dad64acc92700d55240/125516c66e82c728ace21e0d46eb9b97339086ba9cecbb67a549f1d46115743a6b48e13b628ae92dbc56395b4d5a4afa49090c4cf8f18d79f0b339718d5c0becd4380a22ce2f0dbefad341eb5ee779c11ac7a4b6984dc7e23c20e48b884f381c07188efa5c27ed.zip)

**Comment by idelcano** [comment]
@ifoche  all its correct.
that database only contains one local action plan, and i can see that survey with its action plan in the server.

I only needed select the correct filters program, orgunit, and date.


To see that survey in event capture you will need select the filters:
Program "KE HNQIS IMCI"
OrgUnit "__Test KE 3"
Periods: This month 
and the server is clone.psi-mis.

Note: By default all org units are checked, and i needed uncheck  all and check __TestKE3 to see the __TestKE3 events.

![userprovider](https://user-images.githubusercontent.com/5302538/42287436-9c5d133c-7fb6-11e8-9b3f-bd5ba5d044e1.png)

The event is: https://clone.psi-mis.org/api/events/HAl39BfaFaE
(the provider dataelement is VIFKfFTVLcg).

As you see, the provider is in api/event and in event reports.

@ifoche 
do you need more info?

**Comment by ifoche** [comment]
Looks like people were not filling in the field after all. Alpha testers just said it's now working. Thank you so much @idelcano for the investigation
