### ISSUE TITLE
NaN scores

### ISSUE THREAD

**Issue by ifoche** [ifoche/malariapp#2151]
Alpha tester report:

We have noticed that after sometime (not sure how much time), some QoC scores are changing to NaN. When completing surveys, this is not an issue as actual scores display. Later, the scores change to NaN and when you open the assessments whose score is NaN, all sections have 0% scores as though they were never assessed.

[Screenshot 1](https://user-images.githubusercontent.com/26415203/46652872-06489180-cbad-11e8-9213-1ffc2d1b3e4d.jpg)

[Screenshot 2](https://user-images.githubusercontent.com/26415203/46656851-a73c4a00-cbb7-11e8-9f74-dadbdd4db140.png)

**Comment by ifoche** [comment]
[Please find here the DB from the alpha tester](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/54e12dad64acc92700d55240/125516c66e82c728ace21e0d46eb9b97339086ba9cecbb67a549f1d46115713a6b48e13b628ae92dbc56395b4d5a4afa49090c4cf8f18d79f0b339718d5c0becd4380a22ce2f0dbefad341eb5ee779c11ac7a4b6984dc9e23c20e4828f48371b051c8ef85827ed.zip)

**Comment by ifoche** [comment]
Finally only for 1.4

**Comment by idelcano** [comment]
@ifoche I checked each last survey

(uid) -> (result)
nxq7YdgGR5H -> without values, without CS -> NaN
nBWyw3fS2Ix -> CS 80
T6XWVFqocF1 -> CS 89  
ab8ktvex36y -> CS 80
nP8RQb5iWqM -> CS 82
nFgy1D2ahWW -> CS 53
iIOSV7Ssiqz -> CS 97
WH0s6U7OAZk -> CS 55
jN5AWpFlqnz -> CS 67
MxdDO6tvBCV -> without values, without CS
PpAn7NKUE1P -> CS 67
RQwyVc8k5Cs -> one question without nominator, without CS -> NaN 
ibMWKFt81ff -> (one question without nominator, without CS -> NaN 
TLWEaeISlbr -> without values, without CS -> NaN
wbc6pjqOtu9 -> CS 93
UnckjgLXFvW -> CS 53
RseVetHaDNS -> CS 100
wZErWqMdL09 -> without values, without CS -> NaN
tqf8N8tm8ma -> CS 59


When a survey has not score, the survey is pulled without CSs (only the Overall Score is pulled).
If the user creates the survey will be see 0.0 as score in the app.
But if the user pull the survey, the CS root doesn't exist in the server and the Score is null. The user will see NaN as score in the app.

We have three options:

1: (its done in -> https://github.com/EyeSeeTea/malariapp/tree/feature-fix_score_bug_recalculating_scores )
Recalculate Composite Score after pull conversion for every survey without Score.
 -Subtask: Recalculate completed surveys without Score for the logged users. 

2: When the user create a survey without values, show as NaN instead of 0.0.

3: If the survey doesn't have score, push the CSs with 0. But avoid push this CSs is a expected behaviour.

**Comment by ifoche** [comment]
@idelcano their answer:
this is not happening for checklists without scores, the questions in these checklist have scores. A good example is the KE HNQIS IMCI-there is no way you can send this survey without answering the scored questions since they are marked as critical. But if you look at the second screenshot, 2 of these surveys are in that example showing up with NaN score. They initially had a score, then later it changes to NaN

**Comment by ifoche** [comment]
Ok, we have the DB for the second screenshot. 

[compressedData (37).zip](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/54e12dad64acc92700d55240/125516c66e82c728ace21e0d46eb9b97339086ba9cecbb67a549f1d46115703a6b48e13b628ae92dbc56395b4d5a4afa49090c4cf8f18d79f0b339718d5c0becd4380a22ce2f0dbefad341eb5ee779c11ac7a4b6984dc7e23c20e482894f3c1e0c1a80fe5c27ed.zip)
