### ISSUE TITLE
Somalian app crashing

### ISSUE THREAD

**Issue by ifoche** [ifoche/malariapp#2347]
HNQIS version: 1.4.2
server: sm-dev.hnqis.org
user: SMdemo1;xxxxx (sent separately)

**Comment by xurxodev** [comment]
@ifoche After to analyze the crash, the problem is after the pull, the selected org unit previous to crash has not related org unit level in our database. This occurs because the assigned level in server for this org unit is 5 but the org unit levels endpoint retrieves only 4 items.
https://sm-dev.hnqis.org/api/organisationUnits/K4nBuJuDGAO
https://sm-dev.hnqis.org/api/organisationUnitLevels

**Comment by ifoche** [comment]
Thanks @xurxodev
